/* Generated By:JavaCC: Do not edit this line. SmallCCTreeConstants.java Version 6.0_1 */
package compiler;

public interface SmallCCTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTBARETYPE = 1;
  public int JJTTYPE = 2;
  public int JJTVARIABLEDECLARATION = 3;
  public int JJTPREFIXEDVARIABLE = 4;
  public int JJTSUFFIXEDVARIABLE = 5;
  public int JJTVALUE = 6;
  public int JJTINITIALIZATION = 7;
  public int JJTVARIABLES = 8;
  public int JJTFUNCTIONDECLARATION = 9;
  public int JJTPARAMETERLIST = 10;
  public int JJTFUNCTIONDECLARATIONPARAMETER = 11;
  public int JJTFUNCTIONDEFINITION = 12;
  public int JJTFUNCTIONBODY = 13;
  public int JJTFUNCTIONDEFINITIONPARAMETER = 14;
  public int JJTSTATEMENT = 15;
  public int JJTEXPRESSION = 16;
  public int JJTASSIGNMENTEXPRESSION = 17;
  public int JJTTERNARYEXPRESSION = 18;
  public int JJTOREXPRESSION = 19;
  public int JJTANDEXPRESSION = 20;
  public int JJTBITOREXPRESSION = 21;
  public int JJTBITXOREXPRESSION = 22;
  public int JJTBITANDEXPRESSION = 23;
  public int JJTEQUALITYEXPRESSION = 24;
  public int JJTGREATERTHANEXPRESSION = 25;
  public int JJTLESSTHANEXPRESSION = 26;
  public int JJTBITSHIFTEXPRESSION = 27;
  public int JJTADDITIVEEXPRESSION = 28;
  public int JJTMULTIPLICATIVEEXPRESSION = 29;
  public int JJTPREFIXEXPRESSION = 30;
  public int JJTSUFFIXEXPRESSION = 31;
  public int JJTATOMICEXPRESSION = 32;
  public int JJTIDENTIFIER = 33;
  public int JJTCHARACTERCONSTANT = 34;
  public int JJTNUMBER = 35;
  public int JJTSTRINGLITERAL = 36;
  public int JJTBOOLEAN_NOT = 37;
  public int JJTBOOLEAN_AND = 38;
  public int JJTBOOLEAN_OR = 39;
  public int JJTBIT_NOT = 40;
  public int JJTBIT_AND = 41;
  public int JJTBIT_OR = 42;
  public int JJTBIT_XOR = 43;
  public int JJTLEFT_SHIFT = 44;
  public int JJTRIGHT_SHIFT = 45;
  public int JJTR_PAREN = 46;
  public int JJTL_PAREN = 47;
  public int JJTPLUS = 48;
  public int JJTPLUS_PLUS = 49;
  public int JJTMINUS = 50;
  public int JJTMINUS_MINUS = 51;
  public int JJTSTAR = 52;
  public int JJTMOD = 53;
  public int JJTDIVIDE = 54;
  public int JJTEQUALS = 55;
  public int JJTLESS_THAN = 56;
  public int JJTGREATER_THAN = 57;
  public int JJTEQUALS_EQUALS = 58;
  public int JJTNOT_EQUALS = 59;
  public int JJTTOKENS = 60;


  public String[] jjtNodeName = {
    "program",
    "BareType",
    "Type",
    "VariableDeclaration",
    "PrefixedVariable",
    "SuffixedVariable",
    "Value",
    "Initialization",
    "Variables",
    "FunctionDeclaration",
    "ParameterList",
    "FunctionDeclarationParameter",
    "FunctionDefinition",
    "FunctionBody",
    "FunctionDefinitionParameter",
    "Statement",
    "Expression",
    "AssignmentExpression",
    "TernaryExpression",
    "OrExpression",
    "AndExpression",
    "BitOrExpression",
    "BitXorExpression",
    "BitAndExpression",
    "EqualityExpression",
    "GreaterThanExpression",
    "LessThanExpression",
    "BitshiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "PrefixExpression",
    "SuffixExpression",
    "AtomicExpression",
    "Identifier",
    "CharacterConstant",
    "Number",
    "StringLiteral",
    "Boolean_Not",
    "Boolean_And",
    "Boolean_Or",
    "Bit_Not",
    "Bit_And",
    "Bit_Or",
    "Bit_Xor",
    "Left_Shift",
    "Right_Shift",
    "R_Paren",
    "L_Paren",
    "Plus",
    "Plus_Plus",
    "Minus",
    "Minus_Minus",
    "Star",
    "Mod",
    "Divide",
    "Equals",
    "Less_Than",
    "Greater_Than",
    "Equals_Equals",
    "Not_Equals",
    "Tokens",
  };
}
/* JavaCC - OriginalChecksum=808fc1d91a39f9e5d6198ef9e0793710 (do not edit this line) */
