/* Generated By:JavaCC: Do not edit this line. SmallCPPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SmallCPPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRING = 1;
  /** RegularExpression Id. */
  int RESERVED_WORDS = 2;
  /** RegularExpression Id. */
  int IDENTIFIER = 3;
  /** RegularExpression Id. */
  int STRING_LIT_1 = 4;
  /** RegularExpression Id. */
  int STRING_LIT_2 = 5;
  /** RegularExpression Id. */
  int ASM_BLOCK = 6;
  /** RegularExpression Id. */
  int WHITESPACE = 7;
  /** RegularExpression Id. */
  int NEWLINE = 8;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 9;
  /** RegularExpression Id. */
  int VALUE = 10;
  /** RegularExpression Id. */
  int DIGITS = 11;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<STRING>",
    "<RESERVED_WORDS>",
    "<IDENTIFIER>",
    "<STRING_LIT_1>",
    "<STRING_LIT_2>",
    "<ASM_BLOCK>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "<IDENTIFIER_CHAR>",
    "<VALUE>",
    "<DIGITS>",
    "<token of kind 12>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 15>",
  };

}
