/* Generated By:JavaCC: Do not edit this line. SmallCPPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SmallCPPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENTS = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 3;
  /** RegularExpression Id. */
  int STRINGS = 4;
  /** RegularExpression Id. */
  int STATEMENTS = 5;
  /** RegularExpression Id. */
  int RESERVED_WORDS_1 = 6;
  /** RegularExpression Id. */
  int RESERVED_WORDS_2 = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 9;
  /** RegularExpression Id. */
  int STRING_1 = 10;
  /** RegularExpression Id. */
  int STRING_2 = 11;
  /** RegularExpression Id. */
  int ASM_BLOCK = 12;
  /** RegularExpression Id. */
  int VALUE = 13;
  /** RegularExpression Id. */
  int DIGITS = 14;
  /** RegularExpression Id. */
  int WHITESPACE = 15;
  /** RegularExpression Id. */
  int NEWLINE = 16;
  /** RegularExpression Id. */
  int SYMBOLS = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<COMMENTS>",
    "<COMMENT>",
    "<COMMENT_BLOCK>",
    "<STRINGS>",
    "<STATEMENTS>",
    "<RESERVED_WORDS_1>",
    "<RESERVED_WORDS_2>",
    "<IDENTIFIER>",
    "<IDENTIFIER_CHAR>",
    "<STRING_1>",
    "<STRING_2>",
    "<ASM_BLOCK>",
    "<VALUE>",
    "<DIGITS>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "<SYMBOLS>",
  };

}
