/* JavaTokensTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. JavaTokensTokenManager.java */
import java.io.*;

/** Token Manager. */
@SuppressWarnings("unused")public class JavaTokensTokenManager implements JavaTokensConstants {

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
static private int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(3, 0);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 297;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((0xffffffffffffdbffL & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                  }
                  else if (curChar == 10)
                  {
                     if (kind > 11)
                        kind = 11;
                  }
                  else if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 36;
                  if ((0xfc00ffe600000000L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 3)
                        kind = 3;
                     { jjCheckNAdd(21); }
                  }
                  else if ((0x100002400L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                     { jjCheckNAdd(35); }
                  }
                  if (curChar == 47)
                     { jjCheckNAddStates(0, 4); }
                  else if (curChar == 38)
                     { jjCheckNAddTwoStates(29, 53); }
                  else if (curChar == 62)
                     { jjCheckNAddStates(5, 7); }
                  else if (curChar == 60)
                     { jjCheckNAddStates(8, 10); }
                  else if (curChar == 45)
                     { jjCheckNAddTwoStates(43, 29); }
                  else if (curChar == 43)
                     { jjCheckNAddTwoStates(41, 29); }
                  else if (curChar == 33)
                     { jjCheckNAdd(29); }
                  else if (curChar == 37)
                     { jjCheckNAdd(29); }
                  else if (curChar == 61)
                     { jjCheckNAdd(29); }
                  else if (curChar == 42)
                     { jjCheckNAdd(29); }
                  else if (curChar == 39)
                     { jjCheckNAdd(26); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  { jjCheckNAdd(21); }
                  break;
               case 22:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 23:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 24:
                  if (curChar == 34 && kind > 4)
                     kind = 4;
                  break;
               case 25:
                  if (curChar == 39)
                     { jjCheckNAdd(26); }
                  break;
               case 26:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(26, 27); }
                  break;
               case 27:
                  if (curChar == 39 && kind > 5)
                     kind = 5;
                  break;
               case 28:
                  if ((0xfc00ffe600000000L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 29:
                  if (curChar == 61 && kind > 6)
                     kind = 6;
                  break;
               case 30:
                  if (curChar == 42)
                     { jjCheckNAdd(29); }
                  break;
               case 31:
                  if (curChar == 61)
                     { jjCheckNAdd(29); }
                  break;
               case 32:
                  if (curChar == 37)
                     { jjCheckNAdd(29); }
                  break;
               case 34:
                  if (curChar == 33)
                     { jjCheckNAdd(29); }
                  break;
               case 35:
                  if ((0x100002400L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAdd(35); }
                  break;
               case 36:
                  if (curChar == 10 && kind > 11)
                     kind = 11;
                  break;
               case 37:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 10 && kind > 11)
                     kind = 11;
                  break;
               case 39:
                  if ((0xffffffffffffdbffL & l) != 0L && kind > 12)
                     kind = 12;
                  break;
               case 40:
                  if (curChar == 43)
                     { jjCheckNAddTwoStates(41, 29); }
                  break;
               case 41:
                  if (curChar == 43 && kind > 6)
                     kind = 6;
                  break;
               case 42:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(43, 29); }
                  break;
               case 43:
                  if (curChar == 45 && kind > 6)
                     kind = 6;
                  break;
               case 44:
                  if (curChar == 60)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 45:
                  if (curChar == 60 && kind > 6)
                     kind = 6;
                  break;
               case 46:
                  if (curChar == 60)
                     { jjCheckNAdd(29); }
                  break;
               case 47:
                  if (curChar == 62)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 48:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 49:
                  if (curChar == 62)
                     { jjCheckNAdd(29); }
                  break;
               case 52:
                  if (curChar == 38)
                     { jjCheckNAddTwoStates(29, 53); }
                  break;
               case 53:
                  if (curChar == 38 && kind > 6)
                     kind = 6;
                  break;
               case 274:
                  if (curChar == 47)
                     { jjCheckNAddStates(0, 4); }
                  break;
               case 275:
                  if (curChar == 47)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 276:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     { jjCheckNAddStates(11, 13); }
                  break;
               case 277:
               case 279:
                  if (curChar == 10 && kind > 7)
                     kind = 7;
                  break;
               case 278:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 280:
                  if (curChar == 42)
                     { jjCheckNAddStates(14, 17); }
                  break;
               case 281:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddStates(14, 17); }
                  break;
               case 282:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(282, 283); }
                  break;
               case 283:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddStates(14, 17); }
                  break;
               case 284:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 285:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 286:
                  if (curChar == 47)
                     { jjCheckNAddStates(18, 20); }
                  break;
               case 287:
                  if ((0xfffffffffffffbffL & l) != 0L)
                     { jjCheckNAddStates(18, 20); }
                  break;
               case 288:
               case 290:
                  if (curChar == 10 && kind > 8)
                     kind = 8;
                  break;
               case 289:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 288;
                  break;
               case 291:
                  if (curChar == 42)
                     { jjCheckNAddStates(21, 24); }
                  break;
               case 292:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddStates(21, 24); }
                  break;
               case 293:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(293, 294); }
                  break;
               case 294:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddStates(21, 24); }
                  break;
               case 295:
                  if (curChar == 47 && kind > 10)
                     kind = 10;
                  break;
               case 296:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 295;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if (kind > 12)
                     kind = 12;
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 2)
                        kind = 2;
                     { jjCheckNAdd(20); }
                  }
                  else if ((0x7800000068000001L & l) != 0L)
                  {
                     if (kind > 6)
                        kind = 6;
                  }
                  if (curChar == 118)
                     { jjAddStates(25, 26); }
                  else if (curChar == 116)
                     { jjAddStates(27, 32); }
                  else if (curChar == 115)
                     { jjAddStates(33, 38); }
                  else if (curChar == 112)
                     { jjAddStates(39, 41); }
                  else if (curChar == 110)
                     { jjAddStates(42, 44); }
                  else if (curChar == 105)
                     { jjCheckNAddStates(45, 50); }
                  else if (curChar == 102)
                     { jjAddStates(51, 55); }
                  else if (curChar == 101)
                     { jjAddStates(56, 58); }
                  else if (curChar == 100)
                     { jjCheckNAddStates(59, 61); }
                  else if (curChar == 99)
                     { jjAddStates(62, 67); }
                  else if (curChar == 98)
                     { jjAddStates(68, 72); }
                  else if (curChar == 97)
                     { jjAddStates(73, 74); }
                  else if (curChar == 124)
                     { jjCheckNAddTwoStates(29, 51); }
                  else if (curChar == 94)
                     { jjCheckNAdd(29); }
                  else if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 17;
                  else if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 12;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 0:
                  if (curChar == 111 && kind > 1)
                     kind = 1;
                  break;
               case 1:
                  if (curChar == 116)
                     { jjCheckNAdd(0); }
                  break;
               case 2:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  if (curChar == 103 && kind > 1)
                     kind = 1;
                  break;
               case 5:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 7:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 110 && kind > 1)
                     kind = 1;
                  break;
               case 9:
                  if (curChar == 114)
                     { jjCheckNAdd(8); }
                  break;
               case 10:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 101 && kind > 1)
                     kind = 1;
                  break;
               case 15:
               case 115:
               case 268:
                  if (curChar == 108)
                     { jjCheckNAdd(14); }
                  break;
               case 16:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 17:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
               case 20:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  { jjCheckNAdd(20); }
                  break;
               case 23:
                  { jjAddStates(75, 76); }
                  break;
               case 26:
                  { jjAddStates(77, 78); }
                  break;
               case 28:
                  if ((0x7800000068000001L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 33:
                  if (curChar == 94)
                     { jjCheckNAdd(29); }
                  break;
               case 39:
                  if (kind > 12)
                     kind = 12;
                  break;
               case 50:
                  if (curChar == 124)
                     { jjCheckNAddTwoStates(29, 51); }
                  break;
               case 51:
                  if (curChar == 124 && kind > 6)
                     kind = 6;
                  break;
               case 54:
                  if (curChar == 97)
                     { jjAddStates(73, 74); }
                  break;
               case 55:
                  if (curChar == 116 && kind > 1)
                     kind = 1;
                  break;
               case 56:
                  if (curChar == 99)
                     { jjCheckNAdd(55); }
                  break;
               case 57:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 60:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 61:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
               case 158:
               case 213:
                  if (curChar == 114)
                     { jjCheckNAdd(55); }
                  break;
               case 63:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if (curChar == 98)
                     { jjAddStates(68, 72); }
                  break;
               case 67:
               case 76:
                  if (curChar == 97)
                     { jjCheckNAdd(8); }
                  break;
               case 68:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 107 && kind > 1)
                     kind = 1;
                  break;
               case 73:
               case 81:
                  if (curChar == 97)
                     { jjCheckNAdd(72); }
                  break;
               case 74:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 75:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 77:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 82:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 84:
               case 193:
                  if (curChar == 116)
                     { jjCheckNAdd(14); }
                  break;
               case 85:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 86:
                  if (curChar == 99)
                     { jjAddStates(62, 67); }
                  break;
               case 87:
               case 120:
               case 131:
                  if (curChar == 115)
                     { jjCheckNAdd(14); }
                  break;
               case 88:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 104 && kind > 1)
                     kind = 1;
                  break;
               case 90:
               case 230:
                  if (curChar == 99)
                     { jjCheckNAdd(89); }
                  break;
               case 91:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if (curChar == 114 && kind > 1)
                     kind = 1;
                  break;
               case 94:
                  if (curChar == 97)
                     { jjCheckNAdd(93); }
                  break;
               case 95:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 115 && kind > 1)
                     kind = 1;
                  break;
               case 97:
                  if (curChar == 115)
                     { jjCheckNAdd(96); }
                  break;
               case 98:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 115)
                     { jjCheckNAdd(55); }
                  break;
               case 101:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
               case 262:
                  if (curChar == 117)
                     { jjCheckNAdd(14); }
                  break;
               case 104:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 100)
                     { jjCheckNAddStates(59, 61); }
                  break;
               case 110:
                  if (curChar == 108)
                     { jjCheckNAdd(55); }
                  break;
               case 111:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 113:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 114:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 116:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if (curChar == 101)
                     { jjAddStates(56, 58); }
                  break;
               case 121:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if (curChar == 109 && kind > 1)
                     kind = 1;
                  break;
               case 123:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 100)
                     { jjCheckNAdd(96); }
                  break;
               case 126:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 130:
                  if (curChar == 102)
                     { jjAddStates(51, 55); }
                  break;
               case 132:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 108 && kind > 1)
                     kind = 1;
                  break;
               case 135:
                  if (curChar == 97)
                     { jjCheckNAdd(134); }
                  break;
               case 136:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 121 && kind > 1)
                     kind = 1;
                  break;
               case 139:
                  if (curChar == 108)
                     { jjCheckNAdd(138); }
                  break;
               case 140:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if (curChar == 97)
                     { jjCheckNAdd(55); }
                  break;
               case 145:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 146:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 111)
                     { jjCheckNAdd(93); }
                  break;
               case 148:
                  if (curChar == 105)
                     { jjCheckNAddStates(45, 50); }
                  break;
               case 149:
                  if (curChar == 102 && kind > 1)
                     kind = 1;
                  break;
               case 150:
                  if (curChar == 116)
                     { jjCheckNAdd(96); }
                  break;
               case 151:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 155:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 157:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 159:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if (curChar == 111)
                     { jjCheckNAdd(149); }
                  break;
               case 163:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 167:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
               case 255:
                  if (curChar == 110)
                     { jjCheckNAdd(55); }
                  break;
               case 171:
                  if (curChar == 99)
                     { jjCheckNAdd(14); }
                  break;
               case 172:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 110)
                     { jjAddStates(42, 44); }
                  break;
               case 179:
                  if (curChar == 118)
                     { jjCheckNAdd(14); }
                  break;
               case 180:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 182:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 119 && kind > 1)
                     kind = 1;
                  break;
               case 184:
                  if (curChar == 101)
                     { jjCheckNAdd(183); }
                  break;
               case 185:
                  if (curChar == 108)
                     { jjCheckNAdd(134); }
                  break;
               case 186:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if (curChar == 112)
                     { jjAddStates(39, 41); }
                  break;
               case 188:
                  if (curChar == 103)
                     { jjCheckNAdd(14); }
                  break;
               case 189:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 107)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 194:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 197:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 199:
                  if (curChar == 99 && kind > 1)
                     kind = 1;
                  break;
               case 200:
               case 216:
                  if (curChar == 105)
                     { jjCheckNAdd(199); }
                  break;
               case 201:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 206:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 207:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if (curChar == 115)
                     { jjAddStates(33, 38); }
                  break;
               case 214:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 217:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 112 && kind > 1)
                     kind = 1;
                  break;
               case 221:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 225:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 101)
                     { jjCheckNAdd(93); }
                  break;
               case 228:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 231:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 233:
                  if (curChar == 119)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if (curChar == 100 && kind > 1)
                     kind = 1;
                  break;
               case 235:
                  if (curChar == 101)
                     { jjCheckNAdd(234); }
                  break;
               case 236:
                  if (curChar == 122)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 237;
                  break;
               case 239:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 242:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if (curChar == 121)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if (curChar == 116)
                     { jjAddStates(27, 32); }
                  break;
               case 246:
                  if (curChar == 105)
                     { jjCheckNAdd(96); }
                  break;
               case 247:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 111)
                     { jjCheckNAdd(183); }
                  break;
               case 249:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 248;
                  break;
               case 250:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if (curChar == 119)
                     { jjCheckNAdd(96); }
                  break;
               case 252:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 256:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 258:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 258;
                  break;
               case 260:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 259;
                  break;
               case 261:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 260;
                  break;
               case 263:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 264:
                  if (curChar == 114)
                     { jjCheckNAdd(138); }
                  break;
               case 265:
                  if (curChar == 118)
                     { jjAddStates(25, 26); }
                  break;
               case 266:
                  if (curChar == 105)
                     { jjCheckNAdd(234); }
                  break;
               case 267:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 269:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 273:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 276:
                  { jjAddStates(11, 13); }
                  break;
               case 281:
               case 283:
                  { jjCheckNAddStates(14, 17); }
                  break;
               case 287:
                  { jjAddStates(18, 20); }
                  break;
               case 292:
               case 294:
                  { jjCheckNAddStates(21, 24); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 12)
                     kind = 12;
                  break;
               case 23:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(75, 76); }
                  break;
               case 26:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(77, 78); }
                  break;
               case 276:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(11, 13); }
                  break;
               case 281:
               case 283:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(14, 17); }
                  break;
               case 287:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(18, 20); }
                  break;
               case 292:
               case 294:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddStates(21, 24); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 297 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   29, 275, 280, 286, 291, 48, 29, 49, 45, 29, 46, 276, 278, 279, 281, 282, 
   283, 285, 287, 289, 290, 292, 293, 294, 296, 267, 273, 247, 250, 254, 261, 263, 
   264, 215, 219, 226, 229, 233, 244, 192, 197, 211, 182, 184, 186, 149, 157, 161, 
   169, 170, 177, 133, 137, 143, 146, 147, 121, 124, 129, 114, 0, 118, 88, 92, 
   95, 99, 102, 108, 71, 75, 80, 83, 85, 61, 65, 23, 24, 26, 27, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, };
static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public JavaTokensTokenManager(SimpleCharStream stream){

      if (input_stream != null)
        throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);

    input_stream = stream;
  }

  /** Constructor. */
  public JavaTokensTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  static private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 297; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  static public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  static public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
    static protected SimpleCharStream  input_stream;

    static private final int[] jjrounds = new int[297];
    static private final int[] jjstateSet = new int[2 * 297];

    
    static protected char curChar;
}
