/* Generated By:JavaCC: Do not edit this line. SmallCPPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SmallCPPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RESERVED_WORDS = 1;
  /** RegularExpression Id. */
  int IDENTIFIER = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int STRING_LIT = 4;
  /** RegularExpression Id. */
  int CHARACTER = 5;
  /** RegularExpression Id. */
  int SYMBOL = 6;
  /** RegularExpression Id. */
  int COMMENT = 7;
  /** RegularExpression Id. */
  int LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int WHITESPACE = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 10;
  /** RegularExpression Id. */
  int NEWLINE = 11;
  /** RegularExpression Id. */
  int NOT_NEWLINE = 12;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int SYMBOLS = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<RESERVED_WORDS>",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<STRING_LIT>",
    "<CHARACTER>",
    "<SYMBOL>",
    "<COMMENT>",
    "<LINE_COMMENT>",
    "<WHITESPACE>",
    "<MULTI_LINE_COMMENT>",
    "<NEWLINE>",
    "<NOT_NEWLINE>",
    "<IDENTIFIER_CHAR>",
    "<DIGIT>",
    "<SYMBOLS>",
  };

}
