/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 6.0_1 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTADLD = 2;
  public int JJTOPERAND = 3;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "adld",
    "Operand",
  };
}
/* JavaCC - OriginalChecksum=7d130d0c022315d746ca28b82108374e (do not edit this line) */
